### ISSUE TITLE
Float numbers are escaped as strings

### ISSUE THREAD

**Issue by breathbath** [JensRantil/go-csv#16]
When using a dialect like this:

	w := csv2.NewDialectWriter(f, csv2.Dialect{
		Delimiter:      csv2.DefaultDelimiter,
		Quoting:        csv2.QuoteNonNumeric,
		DoubleQuote:    csv2.DoubleQuoteDefault,
		EscapeChar:     csv2.DefaultEscapeChar,
		QuoteChar:      csv2.DefaultQuoteChar,
		LineTerminator: csv2.DefaultLineTerminator,
	})

The floating point numbers are escaped as strings, which is unfortunately not what is expected. The reason for this is this function:

```
func isNumeric(s string) bool {
	if len(s) == 0 {
		return false
	}
	for _, r := range s {
		if !unicode.IsDigit(r) {
			return false
		}
	}
	return true
}
```
which should include . in the filter

**Comment by JensRantil** [comment]
Closed by #17.
