### ISSUE TITLE
QuoteMinimal mode doesn't check for leading/trailing whitespaces

### ISSUE THREAD

**Issue by ssi-hu-laszlo-vegh** [JensRantil/go-csv#18]
When writing a row which contains the following strings:
"1", "2", " text ","3"

The expected output is:
1,2," text ",3

But the actual output is:
1,2, text ,3

**Comment by JensRantil** [comment]
Whoa! Thanks!

**Comment by JensRantil** [comment]
I was inspired by the Python `csv` library when when I wrote this library. Based on https://docs.python.org/2/library/csv.html#csv.QUOTE_MINIMAL, it looks like that one doesn't quote when there are spaces before and after the `,`:

> Instructs writer objects to only quote those fields which contain special characters such as delimiter, quotechar or any of the characters in lineterminator.

The more I think about it, it shouldn't be needed to quote spaces (unless they are part of the delimiter or line terminator), right?

**Comment by JensRantil** [comment]
If you really want quotes, I'd recommend using `QuoteAll`.

**Comment by JensRantil** [comment]
I'll be closing this as no response. Please reopen if still relevant.
